### ISSUE TITLE
ENH: need way to reconnect to cloud

### ISSUE THREAD

**Issue by jschrempp** [BobGlicksman/Robotics#17]
We currently run with SYSTEM_MODE(SEMI_AUTOMATIC); so that the robot will run without a WiFi connection. This is fine. But to push new firmware requires a two button boot into safe mode so the Photon will connect to the cloud. 

It would be nice to have a pushbutton on the device. When pushed a routine would fire to do a Particle.connect(). This would allow a one button push to connect to the cloud. Also good if you want to control the robot through the Particle console.

**Comment by BobGlicksman** [comment]
J17 - Photon Expansion - exposes pins A2 through A5 and includes 2 gnd pins. Solder header pins to this field and you can wire in some sort of switch. I suggest a toggle switch rather than a pushbutton. Read it during setup() to set the system mode. A small panel mount toggle ( such as we used on WLD) could be mounted through a hole on the robot chassis near the pcb.
I like this solution, albeit we would need to reset the photon when changing the switch position. It nicely supports both modes of operation without a lot of hassle.


-----Original Message-----

**Comment by BobGlicksman** [comment]
If you use this solution, use pinMode(A2, INPUT_PULLUP); in setup() and have the toggle switch ground A2 when the switch is activated.  I request that you make the mode if(digitalRead(A2) == HIGH) put the photon in semi-automatic mode and if(digitalRead(A2 == LOW) put it in automatic mode.  This way, if I don't install a switch, the default will be semi-automatic mode.

**Comment by BobGlicksman** [comment]
Here is my suggested solution:

![Toggle_suggestion](https://user-images.githubusercontent.com/16446510/91780523-a4341380-ebac-11ea-9664-504601e54c1b.png)

**Comment by BobGlicksman** [comment]
Alternatively, just use a jumper on the J17 pin header to ground A2 for automatic mode.  Unless you want to change the mode a lot, there is no need to mount a switch.
